name: example_server
version: 1.0.0
description: Dart SDK implementation for FeatureHub - open source Feature Flag management, A/B testing and remote configuration platform. Suitable for Flutter Web, Mobile and Desktop.
repository: https://github.com/featurehub-io/featurehub-flutter-sdk/tree/main/featurehub-client-sdk
homepage: https://www.featurehub.io
environment:
  sdk: '>2.17.0 <3.1.0'
dependencies:
  collection: ^1.15.0
  logging: ^1.0.1
  rxdart: ^0.27.2
  featurehub_client_sdk:
    path: ../../featurehub-client-sdk
  openapi_dart_common: ^5.0.0
  shelf_router: ^1.1.3
dev_dependencies:
  test: ^1.16.8
  #  test_coverage: ^0.4.2
  mocktail: 0.1.4
  pedantic: ^1.11.0
