name: featurehub_client_api
version: 1.5.0
description: This is the OpenAPI client for the FeatureHub SDK. It is not likely to be used on its own.
repository: https://github.com/featurehub-io/featurehub/tree/master/sdks/dart/client-dart-api
homepage: https://www.featurehub.io
environment:
  sdk: '>=2.15.0 <3.1.0'
dependencies:
  dio: '^5.0.1'
  openapi_dart_common: ^5.0.0
  collection: '^1.16.0'
dev_dependencies:
  test: ^1.23.1
  flutter_lints: ^2.0.1
# bought to you by the folks from FeatureHub https://featurehub.io
