name: featurehub_client_sdk
version: 2.0.0
description: Dart SDK implementation for FeatureHub - open source Feature Flag management, A/B testing and remote configuration platform. Suitable for Flutter Web, Mobile and Desktop.
repository: https://github.com/featurehub-io/featurehub-flutter-sdk/tree/main/featurehub-client-sdk
homepage: https://www.featurehub.io
environment:
  sdk: '>2.17.0 <3.1.0'
dependencies:
  dio: '^5.0.1'
  openapi_dart_common: ^5.0.0
  crypto: ^3.0.2
#  featurehub_sse_client: ^1.3.2
  featurehub_sse_client:
    path: ../featurehub-sse-client
  collection: ^1.15.0
  logging: ^1.0.1
  rxdart: ^0.27.2
  meta: ^1.8.0
  murmur3: ^2.1.0
  featurehub_usage_api:
    path: ../featurehub-usage-api
#  featurehub_client_api: ^1.5.0
  featurehub_client_api:
    path: ../featurehub-client-api
dev_dependencies:
  file: ^6.1.4
  mocktail: 0.3.0
  test: ^1.23.1
  flutter_lints: ^2.0.1
