name: featurehub_client_sdk
version: 1.3.0
description: Dart SDK implementation for FeatureHub - open source Feature Flag management, A/B testing and remote configuration platform. Suitable for Flutter Web, Mobile and Desktop.
repository: https://github.com/featurehub-io/featurehub-flutter-sdk/tree/main/featurehub-client-sdk
homepage: https://www.featurehub.io
environment:
  sdk: '>2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  featurehub_sse_client: ^1.3.0
#  featurehub_sse_client:
#    path: ../featurehub-sse-client
  collection: ^1.15.0
  logging: ^1.0.1
  rxdart: ^0.27.2
  featurehub_client_api: ^1.3.0
#  featurehub_client_api:
#    path: ../featurehub-client-api
  openapi_dart_common: ^4.1.0
dev_dependencies:
  test: ^1.16.8
#  test_coverage: ^0.4.2
  mocktail: 0.1.4
  pedantic: ^1.11.0
